# Generated by Django 6.0 on 2025-12-10 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_search_optimization_indices"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="listing",
            name="listings_price_idx",
        ),
        migrations.RemoveIndex(
            model_name="listing",
            name="listings_location_idx",
        ),
        migrations.RemoveIndex(
            model_name="listing",
            name="listings_category_fk_idx",
        ),
        migrations.RemoveIndex(
            model_name="listing",
            name="listings_created_desc_idx",
        ),
        migrations.RemoveIndex(
            model_name="listing",
            name="listings_filter_combo_idx",
        ),
        migrations.RemoveIndex(
            model_name="listing",
            name="listings_geo_idx",
        ),
        migrations.RemoveIndex(
            model_name="listing",
            name="listings_type_idx",
        ),
        migrations.RemoveIndex(
            model_name="listing",
            name="listings_boosted_idx",
        ),
        migrations.RemoveIndex(
            model_name="listing",
            name="listings_views_idx",
        ),
    ]
