# Generated by Django 6.0 on 2025-12-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0003_remove_listing_listings_price_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="condition",
            field=models.CharField(
                choices=[
                    ("new", "Neuf"),
                    ("like_new", "Comme neuf"),
                    ("good", "Bon état"),
                    ("fair", "État correct"),
                    ("poor", "Usé"),
                ],
                default="good",
                max_length=20,
            ),
        ),
    ]
