# Generated by Django 6.0 on 2025-12-10 04:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("listings", "0003_remove_listing_listings_price_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("percentage", "Pourcentage"), ("fixed", "Montant fixe")],
                        max_length=20,
                    ),
                ),
                ("discount_value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("applies_to_subscription", models.BooleanField(default=True)),
                ("applies_to_post_credit", models.BooleanField(default=True)),
                ("max_uses", models.IntegerField(blank=True, null=True)),
                ("uses_count", models.IntegerField(default=0)),
                ("max_uses_per_user", models.IntegerField(default=1)),
                ("valid_from", models.DateTimeField()),
                ("valid_until", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("stripe_coupon_id", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "payments_coupon",
            },
        ),
        migrations.CreateModel(
            name="PostCreditPack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("credits", models.IntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stripe_price_id", models.CharField(blank=True, db_index=True, max_length=100)),
                ("stripe_product_id", models.CharField(blank=True, max_length=100)),
                ("bonus_credits", models.IntegerField(default=0)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_popular", models.BooleanField(default=False)),
                ("sort_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "payments_postcreditpack",
                "ordering": ["sort_order", "price"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="EUR", max_length=3)),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("subscription", "Abonnement"),
                            ("post_credit", "Crédit annonce"),
                            ("boost", "Boost annonce"),
                            ("commission", "Commission"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("processing", "En cours"),
                            ("completed", "Complété"),
                            ("failed", "Échoué"),
                            ("refunded", "Remboursé"),
                            ("cancelled", "Annulé"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "stripe_checkout_session_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("stripe_customer_id", models.CharField(blank=True, max_length=100)),
                ("stripe_invoice_id", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "listing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="listings.listing",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payments_payment",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("invoice_number", models.CharField(max_length=100, unique=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("tax_amount", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                ("due_at", models.DateTimeField()),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("pdf_file", models.FileField(blank=True, null=True, upload_to="invoices/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "db_table": "payments_invoice",
                "ordering": ["-issued_at"],
            },
        ),
        migrations.CreateModel(
            name="PostCredit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("balance", models.IntegerField(default=0)),
                ("total_purchased", models.IntegerField(default=0)),
                ("total_used", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_credits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payments_postcredit",
            },
        ),
        migrations.CreateModel(
            name="PostCreditTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("purchase", "Achat"),
                            ("use", "Utilisation"),
                            ("refund", "Remboursement"),
                            ("bonus", "Bonus"),
                            ("expiry", "Expiration"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.IntegerField()),
                ("balance_after", models.IntegerField()),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "listing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="credit_transactions",
                        to="listings.listing",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="credit_transactions",
                        to="payments.payment",
                    ),
                ),
                (
                    "post_credit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="payments.postcredit",
                    ),
                ),
            ],
            options={
                "db_table": "payments_postcredittransaction",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                (
                    "plan_type",
                    models.CharField(
                        choices=[("basic", "Basic"), ("pro", "Pro"), ("business", "Business")],
                        max_length=20,
                    ),
                ),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[("monthly", "Mensuel"), ("yearly", "Annuel")], max_length=20
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stripe_price_id", models.CharField(blank=True, db_index=True, max_length=100)),
                ("stripe_product_id", models.CharField(blank=True, max_length=100)),
                ("max_listings", models.IntegerField(default=5)),
                ("max_images_per_listing", models.IntegerField(default=5)),
                ("can_boost", models.BooleanField(default=False)),
                ("boost_count_per_month", models.IntegerField(default=0)),
                ("featured_badge", models.BooleanField(default=False)),
                ("priority_support", models.BooleanField(default=False)),
                ("analytics_access", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True)),
                ("features_list", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("is_popular", models.BooleanField(default=False)),
                ("sort_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "payments_subscriptionplan",
                "ordering": ["sort_order", "price"],
                "unique_together": {("plan_type", "billing_cycle")},
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Actif"),
                            ("trialing", "Période d'essai"),
                            ("past_due", "Paiement en retard"),
                            ("cancelled", "Annulé"),
                            ("expired", "Expiré"),
                            ("paused", "En pause"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "stripe_subscription_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("stripe_customer_id", models.CharField(blank=True, max_length=100)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("current_period_start", models.DateTimeField(blank=True, null=True)),
                ("current_period_end", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("trial_ends_at", models.DateTimeField(blank=True, null=True)),
                ("listings_used", models.IntegerField(default=0)),
                ("boosts_used", models.IntegerField(default=0)),
                ("auto_renew", models.BooleanField(default=True)),
                ("cancel_at_period_end", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="payments.subscriptionplan",
                    ),
                ),
            ],
            options={
                "db_table": "payments_subscription",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="payment",
            name="subscription_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="payments.subscriptionplan",
            ),
        ),
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("stripe_event_id", models.CharField(db_index=True, max_length=100, unique=True)),
                ("event_type", models.CharField(db_index=True, max_length=100)),
                ("payload", models.JSONField()),
                ("processed", models.BooleanField(default=False)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("retry_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "payments_webhookevent",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "-created_at"], name="payments_we_event_t_8f0131_idx"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["user", "-created_at"], name="payments_pa_user_id_7a85fd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["status"], name="payments_pa_status_7ad4af_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["payment_type"], name="payments_pa_payment_09c1c1_idx"),
        ),
    ]
