# Generated by Django 6.0 on 2025-12-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("subscription", "Abonnement"),
                    ("post_credit", "Crédit annonce"),
                    ("boost", "Boost annonce"),
                    ("commission", "Commission"),
                    ("purchase", "Achat article"),
                ],
                max_length=20,
            ),
        ),
    ]
