# Generated by Django - orders migration

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('status', models.CharField(choices=[
                    ('pending', 'En attente de confirmation'),
                    ('confirmed', 'Confirmée'),
                    ('processing', 'En préparation'),
                    ('shipped', 'Expédiée'),
                    ('delivered', 'Livrée'),
                    ('completed', 'Terminée'),
                    ('cancelled', 'Annulée'),
                    ('refunded', 'Remboursée'),
                    ('disputed', 'Litige'),
                ], db_index=True, default='pending', max_length=20)),
                ('listing_title', models.CharField(max_length=200)),
                ('listing_snapshot', models.JSONField(blank=True, default=dict, help_text='Snapshot de l\'annonce au moment de l\'achat')),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('platform_fee_percent', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('seller_amount', models.DecimalField(decimal_places=2, help_text='Montant qui revient au vendeur', max_digits=10)),
                ('delivery_type', models.CharField(choices=[
                    ('shipping', 'Expédition'),
                    ('local', 'Remise en main propre'),
                ], default='shipping', max_length=20)),
                ('shipping_address', models.JSONField(blank=True, default=dict)),
                ('tracking_number', models.CharField(blank=True, max_length=100)),
                ('carrier', models.CharField(blank=True, max_length=50)),
                ('tracking_url', models.URLField(blank=True)),
                ('seller_notes', models.TextField(blank=True, help_text='Notes du vendeur')),
                ('buyer_notes', models.TextField(blank=True, help_text="Notes de l'acheteur")),
                ('internal_notes', models.TextField(blank=True, help_text='Notes internes (admin)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('seller_notified', models.BooleanField(default=False)),
                ('buyer_confirmed_receipt', models.BooleanField(default=False)),
                ('funds_released', models.BooleanField(default=False)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders_as_buyer', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='listings.listing')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='payments.payment')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders_as_seller', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'db_table': 'orders_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SellerWallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, default=0, help_text='Solde disponible', max_digits=10)),
                ('pending_balance', models.DecimalField(decimal_places=2, default=0, help_text='En attente de confirmation', max_digits=10)),
                ('total_earned', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_withdrawn', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_holder', models.CharField(blank=True, max_length=200)),
                ('iban', models.CharField(blank=True, max_length=34)),
                ('bic', models.CharField(blank=True, max_length=11)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Portefeuille vendeur',
                'verbose_name_plural': 'Portefeuilles vendeurs',
                'db_table': 'orders_sellerwallet',
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[
                    ('pending', 'En attente'),
                    ('processing', 'En cours de traitement'),
                    ('completed', 'Effectué'),
                    ('rejected', 'Rejeté'),
                    ('cancelled', 'Annulé'),
                ], db_index=True, default='pending', max_length=20)),
                ('bank_details', models.JSONField(default=dict, help_text='Copie des informations bancaires au moment de la demande')),
                ('user_notes', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('transfer_reference', models.CharField(blank=True, help_text='Référence du virement', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='orders.sellerwallet')),
            ],
            options={
                'verbose_name': 'Demande de retrait',
                'verbose_name_plural': 'Demandes de retrait',
                'db_table': 'orders_withdrawalrequest',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[
                    ('sale', 'Vente'),
                    ('withdrawal', 'Retrait'),
                    ('refund', 'Remboursement'),
                    ('adjustment', 'Ajustement'),
                    ('fee', 'Frais'),
                ], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='orders.order')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='orders.sellerwallet')),
                ('withdrawal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='orders.withdrawalrequest')),
            ],
            options={
                'verbose_name': 'Transaction wallet',
                'verbose_name_plural': 'Transactions wallet',
                'db_table': 'orders_wallettransaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['buyer', 'status'], name='orders_orde_buyer_i_7f8e0c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['seller', 'status'], name='orders_orde_seller__e2c3f1_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='orders_orde_created_51d5ac_idx'),
        ),
    ]
