# Generated by Django 6.0 on 2025-12-10 10:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("listings", "0003_remove_listing_listings_price_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ListingStats",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("total_views", models.IntegerField(default=0)),
                ("total_clicks", models.IntegerField(default=0)),
                ("total_favorites", models.IntegerField(default=0)),
                ("total_shares", models.IntegerField(default=0)),
                ("total_contacts", models.IntegerField(default=0)),
                ("unique_views", models.IntegerField(default=0)),
                ("unique_clicks", models.IntegerField(default=0)),
                ("conversion_rate", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "listing",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="listings.listing",
                    ),
                ),
            ],
            options={
                "db_table": "analytics_listingstats",
            },
        ),
        migrations.CreateModel(
            name="DailyStats",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("listing_views", models.IntegerField(default=0)),
                ("listing_clicks", models.IntegerField(default=0)),
                ("profile_views", models.IntegerField(default=0)),
                ("messages_received", models.IntegerField(default=0)),
                ("messages_sent", models.IntegerField(default=0)),
                ("favorites_received", models.IntegerField(default=0)),
                ("payments_received", models.IntegerField(default=0)),
                ("revenue", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("reviews_received", models.IntegerField(default=0)),
                ("avg_rating_day", models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_stats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "analytics_dailystats",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(fields=["user", "date"], name="analytics_d_user_id_418a05_idx")
                ],
                "unique_together": {("user", "date")},
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("listing_view", "Vue d'annonce"),
                            ("listing_click", "Clic sur annonce"),
                            ("listing_contact", "Contact vendeur"),
                            ("listing_favorite", "Ajout favori"),
                            ("listing_share", "Partage annonce"),
                            ("message_sent", "Message envoyé"),
                            ("message_received", "Message reçu"),
                            ("payment_initiated", "Paiement initié"),
                            ("payment_completed", "Paiement complété"),
                            ("review_received", "Avis reçu"),
                            ("profile_view", "Vue profil vendeur"),
                            ("search", "Recherche"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("session_id", models.CharField(blank=True, db_index=True, max_length=100)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("referrer", models.URLField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "listing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="listings.listing",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "analytics_event",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "created_at"], name="analytics_e_event_t_ef40a5_idx"
                    ),
                    models.Index(
                        fields=["target_user", "event_type", "created_at"],
                        name="analytics_e_target__186610_idx",
                    ),
                    models.Index(
                        fields=["listing", "event_type", "created_at"],
                        name="analytics_e_listing_be7c15_idx",
                    ),
                ],
            },
        ),
    ]
